<a href="https://colab.research.google.com/github/madanjha/Machine-Learning/blob/main/Hyperparameter_and_optimization_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Foundation**
###**What is Optimization**
The main goal of machine learning is to create a model that generalize well to the new or unseen data.

**Optimization is the process of finding the best possible model which help us to achive our ML Goal**

###**Parameter**
The things that model learns from the data

* **Let's say i am cooking Soup, I will be adding the salt according to my taste** -> Here the salt value is what **`Parameter`**
    * Technically -> The Coefficients in linear regression (m,c) and the weights in a neural network (y = wx + b). Thse are the parameters that are learned during the `.fit()` process

###**Hyperparameters**
Setting you tell the model before it starts learning is hyperparameter
* The Recipe instructions we set before cooking (temperature of oven, timer -> 30 mins)
    * Techinically -> The `n_estimators`(number of tree) in a Random Forest, The `C Parameter` (regularization strength) in support Vector Machine, In Gradient Descent we have `learning_rate`

**The Problem That we need to handle**
###**Overfitting**
When the model is too complex. It Learns the training data and it's noise aswell. it fails to generalize the new data (High Variance)
* Let's say we are memorizing the answers for the practice exam but not learning the concepts, so in Real exam you can fail

###**Underfitting**
**When the model is too simle and fails to learn the hidden patterns in trainin data. (High Bias)**

**Note:** Hyperparameter tuning is the process of finding the best settings to create a nodel that is `'Good'`

###**How we measure **GOOD** : Cross validation**
We cannot use the test set of the dataset to tune our hyperparamter. As it is like a cheating for getting good results on my testing data

**We use K-fold Cross Validation**
1. Split the training data into 'k' folds (k = 5)
2. Train the model on 4 folds, validates on the 1 held-out fold
3. Repeate 5 times, holding out a different folds each time
4. The score to set the values of hyperparmeter is the average score of all 5 folds

It gives us a good estiamte of how the model will perform on unseen data

**Import Libraries**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

**Load and prepare the data**

In [ ]:
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

**since our data is in JSON Format, we will extract X and Y from the data**

In [ ]:
x = data.data
y = data.target

In [ ]:
pd.DataFrame(x)

        0      1       2       3   ...      26      27      28       29
0    17.99  10.38  122.80  1001.0  ...  0.7119  0.2654  0.4601  0.11890
1    20.57  17.77  132.90  1326.0  ...  0.2416  0.1860  0.2750  0.08902
2    19.69  21.25  130.00  1203.0  ...  0.4504  0.2430  0.3613  0.08758
3    11.42  20.38   77.58   386.1  ...  0.6869  0.2575  0.6638  0.17300
4    20.29  14.34  135.10  1297.0  ...  0.4000  0.1625  0.2364  0.07678
..     ...    ...     ...     ...  ...     ...     ...     ...      ...
564  21.56  22.39  142.00  1479.0  ...  0.4107  0.2216  0.2060  0.07115
565  20.13  28.25  131.20  1261.0  ...  0.3215  0.1628  0.2572  0.06637
566  16.60  28.08  108.30   858.1  ...  0.3403  0.1418  0.2218  0.07820
567  20.60  29.33  140.10  1265.0  ...  0.9387  0.2650  0.4087  0.12400
568   7.76  24.54   47.92   181.0  ...  0.0000  0.0000  0.2871  0.07039

[569 rows x 30 columns]

In [ ]:
pd.DataFrame(y)

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

**Split the data into Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score

We will split once and hold the test set aside

In [ ]:
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
x_train

array([[1.032e+01, 1.635e+01, 6.531e+01, ..., 2.381e-02, 2.681e-01,
        7.399e-02],
       [2.018e+01, 1.954e+01, 1.338e+02, ..., 2.173e-01, 3.032e-01,
        8.075e-02],
       [1.066e+01, 1.515e+01, 6.749e+01, ..., 0.000e+00, 2.710e-01,
        6.164e-02],
       ...,
       [1.546e+01, 2.395e+01, 1.038e+02, ..., 2.163e-01, 3.013e-01,
        1.067e-01],
       [1.705e+01, 1.908e+01, 1.134e+02, ..., 2.543e-01, 3.109e-01,
        9.061e-02],
       [1.088e+01, 1.562e+01, 7.041e+01, ..., 7.966e-02, 2.581e-01,
        1.080e-01]])

In [ ]:
x_test

array([[1.955e+01, 2.877e+01, 1.336e+02, ..., 1.941e-01, 2.818e-01,
        1.005e-01],
       [1.113e+01, 1.662e+01, 7.047e+01, ..., 4.044e-02, 2.383e-01,
        7.083e-02],
       [1.382e+01, 2.449e+01, 9.233e+01, ..., 1.521e-01, 3.651e-01,
        1.183e-01],
       ...,
       [1.532e+01, 1.727e+01, 1.032e+02, ..., 2.229e-01, 3.258e-01,
        1.191e-01],
       [1.262e+01, 2.397e+01, 8.135e+01, ..., 1.180e-01, 2.826e-01,
        9.585e-02],
       [1.168e+01, 1.617e+01, 7.549e+01, ..., 9.815e-02, 2.804e-01,
        8.024e-02]])

In [ ]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
y_test

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1])

Since the data varies alot, we will scale the data as it is very important for SVMs

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
x_train_scaled

array([[-1.07200079, -0.6584246 , -1.0880801 , ..., -1.35052668,
        -0.35265805, -0.54138003],
       [ 1.74874285,  0.06650173,  1.75115682, ...,  1.54991557,
         0.19107787, -0.1737386 ],
       [-0.97473376, -0.93112416, -0.99770871, ..., -1.70744192,
        -0.307734  , -1.21303263],
       ...,
       [ 0.39844772,  1.06867262,  0.50751384, ...,  1.53492543,
         0.16164487,  1.23754763],
       [ 0.85331409, -0.0380331 ,  0.9054796 , ...,  2.10455077,
         0.31035897,  0.36249578],
       [-0.91179628, -0.82431683, -0.87666079, ..., -0.51332734,
        -0.50756857,  1.30824791]])

In [ ]:
x_test_scaled

array([[ 1.56851278,  2.16401585,  1.74286587, ...,  1.20214432,
        -0.14043064,  0.90036171],
       [-0.84027641, -0.5970672 , -0.8741735 , ..., -1.10124064,
        -0.81429139, -0.71323608],
       [-0.07072262,  1.19138742,  0.03202768, ...,  0.57255843,
         1.14997397,  1.86841162],
       ...,
       [ 0.3583966 , -0.44935493,  0.48264098, ...,  1.63386036,
         0.54117564,  1.91191948],
       [-0.41401799,  1.07321761, -0.42314565, ...,  0.06139464,
        -0.1280378 ,  0.64747227],
       [-0.6829327 , -0.69932953, -0.66607058, ..., -0.23615965,
        -0.16211811, -0.20147486]])

**Build model**

In [ ]:
from sklearn.svm import SVC

In [ ]:
baseModel = SVC(random_state=42)

**Now we will find the cross validation score**

In [ ]:
cv_score = cross_val_score(baseModel, x_train_scaled,y_train, cv = 5)

In [ ]:
cv_score

array([0.95604396, 0.98901099, 0.94505495, 0.97802198, 0.98901099])

In [ ]:
print(f'Default CV Accuracy : {np.mean(cv_score):.2f} +/- {np.std(cv_score):.2f}')

Default CV Accuracy : 0.97 +/- 0.02

**Let's Do on final testing data**

In [ ]:
baseModel.fit(x_train_scaled,y_train)

SVC(random_state=42)

In [ ]:
y_pred = baseModel.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
test_accuracy = accuracy_score(y_test,y_pred)
print(f'Default Test set Accuracy: {test_accuracy:}')

Default Test set Accuracy: 0.9824561403508771

##**Core Tuning Methods**
###1. GridSearchCV (Exhaustive Search)
We define a grid with all possible hyperparameter combinations that we want to try

**How it Works**
* It trains and evaluates a model for every single combinations in the grid using Cross validation
* pros: Very easy for understanding and it gives gaurantee to find the best combinations within your grid
* cons: It is extremly slow and suffers from the 'Curse of Dimensionality'.
if you have 3 parameters with 10 values each, `10 * 10 * 10 = 1000` Models to train (times of k folds)

###2. RandomizedSearchCV (Smart Sampling)
We will define a 'distribution' or 'list' for each hyperparameters. Then it will sample a fixed number(n_iter) of random combination from these distributions

**How it Works**
* let's say we gave `n_iter = 50`
* It will randomly picks 50 different combinations
* train them and report the best one

**Pros**
* Much Faster
* Not all hyperparameters are equally important. Random Search is most likely to find 'Good Enough' value for the important parameters, rather than wasitng time tesing many 'bad' values for unimportant parameters

**Cons**
* It does not guaranteed to find the best combinations

**To implement RandomSearch CV and Grid Search CV**

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy.stats import uniform, loguniform # For random search distribution

**We will be using the same Scaled Training Data from the above code**

In [ ]:
x_train_scaled , y_train

(array([[-1.07200079, -0.6584246 , -1.0880801 , ..., -1.35052668,
         -0.35265805, -0.54138003],
        [ 1.74874285,  0.06650173,  1.75115682, ...,  1.54991557,
          0.19107787, -0.1737386 ],
        [-0.97473376, -0.93112416, -0.99770871, ..., -1.70744192,
         -0.307734  , -1.21303263],
        ...,
        [ 0.39844772,  1.06867262,  0.50751384, ...,  1.53492543,
          0.16164487,  1.23754763],
        [ 0.85331409, -0.0380331 ,  0.9054796 , ...,  2.10455077,
          0.31035897,  0.36249578],
        [-0.91179628, -0.82431683, -0.87666079, ..., -0.51332734,
         -0.50756857,  1.30824791]]),
 array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
        0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
        0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]))

**GridSearchCV**

In [ ]:
svc = SVC(random_state=42)

**Define the 'grid' of hyperparameter to test**

In [ ]:
param_grid = {
    'C': [0.1,1,10,100],
    'gamma': [1,0.1,0.01,0.001],
    'kernel': ['rbf','sigmoid']
}
# 4 (C) * 4 (gamma) * 2 (Kernals) * 5 (CV) = 160 models

**Now, we will setup the gridsearchCV**

In [ ]:
grid_search = GridSearchCV(estimator=svc,
                           param_grid = param_grid,
                           cv = 5, # We are creating five folds in training data for validation
                           n_jobs = -1, # It means we are using all the available CPU cores
                           verbose = 1) # verbose shows the progess

**Run the search**

In [ ]:
grid_search.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

GridSearchCV(cv=5, estimator=SVC(random_state=42), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'sigmoid']},
             verbose=1)

In [ ]:
print(f'GridSearch Best Score (CV Accuracy): {grid_search.best_score_:.2f}')
print(f'GridSeach Best Params: {grid_search.best_params_}')

GridSearch Best Score (CV Accuracy): 0.98
GridSeach Best Params: {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

**RandomSearchCV**

First, we will define the 'distributions' to sample from. It will give us much wider range to explore

In [ ]:
param_dist = {
    'C': loguniform(1e-1, 1e2), # sample from 0.1 to 100
    'gamma': loguniform(1e-3,1e0), # sample from 0.001 to 1
    'kernel': ['rbf','sigmoid']
}

**Now we will setup our RandomSearchCV**
* n_iter = 50 --> It will try 50 random combination
* total models trained = 50 (n_iter) * 5(cv) = 250 models
* This is more than GridSearchCV, but explores a **much** wider space

In [ ]:
random_search = RandomizedSearchCV(estimator=svc,
                                   param_distributions = param_dist,
                                   n_iter = 50,
                                   cv = 5,
                                   n_jobs = -1,
                                   verbose = 1,
                                   random_state = 42)

Run the search

In [ ]:
random_search.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

RandomizedSearchCV(cv=5, estimator=SVC(random_state=42), n_iter=50, n_jobs=-1,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7e872a979b80>,
                                        'gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7e872a97a240>,
                                        'kernel': ['rbf', 'sigmoid']},
                   random_state=42, verbose=1)

In [ ]:
print(f'RandomSearch Best Score (CV Accuracy): {random_search.best_score_:.2f}')
print(f'RandomSearch Best Params: {random_search.best_params_}')

RandomSearch Best Score (CV Accuracy): 0.98
RandomSearch Best Params: {'C': np.float64(20.73644517790503), 'gamma': np.float64(0.0039459088110999985), 'kernel': 'sigmoid'}

**Final Evalutation**

In [ ]:
best_model = grid_search.best_estimator_ # or random_search.best_estimator_

In [ ]:
final_y_pred = best_model.predict(x_test_scaled)

In [ ]:
final_y_pred

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1])

In [ ]:
final_accuracy = accuracy_score(y_test,final_y_pred)

In [ ]:
print(f'BaseModel Test Accuracy: {test_accuracy:.4f}')
print(f'Tuned Test Accuracy: {final_accuracy:.4f}')

BaseModel Test Accuracy: 0.9825
Tuned Test Accuracy: 0.9825

##**Other Optimization Techniques**
Hyperparameter tuning is not the only wat to optimize the model. We also optimize the model's parameter and structure

###**Gradient Descent**
This is the algorithm that perfoms the leaning(finds the paramater) for most models like linear Regression, logistic Regression, Neural Network

**Goal** - To minimize the Loss function **(`J(0)` -> It is basically a mathematic function that measures how wrong the model predictions are)**

###**Regularization**
It is a technique to prevent Overfitting by penalizing the complex model.

`cost = loss(how wrong we are) + lambda * Penality(How complex we are)`
* lambda -> The regularization strength

**It has two types based on penalizing way**
1. L2 Regularization (Rigid):
    * Penality is the sum of the squared weights
    * It basically shrinks the weights but not make it 0

2. L1 Regularization (Lasso):
    * Penality is the sum of absolute values of the weights
    * It forces many weights to be exaclty zero
    * It automatically does feature selection, if weight of feature is zero -> unimportant

In [ ]:
from sklearn.linear_model import LogisticRegression, SGDClassifier

**Logistic Reg has builtin regularization**
* 'C' is the 'inverse' of regularization strenght (small C = Strong Regularization)

In [ ]:
log_reg = LogisticRegression(solver='liblinear',random_state=42, max_iter=1000)

In [ ]:
reg_para_grid = {
    'C' : [0.01,0.1,1,10,100],
    'penalty' : ['l1','l2']
}

In [ ]:
reg_grid_seach = GridSearchCV(log_reg,
                              reg_para_grid,
                              cv = 5,
                              n_jobs = -1,
                              verbose = 1)

In [ ]:
reg_grid_seach.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

GridSearchCV(cv=5,
             estimator=LogisticRegression(max_iter=1000, random_state=42,
                                          solver='liblinear'),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']},
             verbose=1)

In [ ]:
print(f'Best Regularization Score: {reg_grid_seach.best_score_:.2f}')
print(f'Best Regularization params: {reg_grid_seach.best_params_}')

Best Regularization Score: 0.98
Best Regularization params: {'C': 1, 'penalty': 'l2'}

**Now I will build SGD model**

In [ ]:
sgd_model = SGDClassifier(loss = 'log_loss',
                          penalty='l2',
                          max_iter = 1000,
                          tol = 1e-3)

In [ ]:
sgd_model.fit(x_train_scaled,y_train)

SGDClassifier(loss='log_loss')

In [ ]:
y_pred_sgd = sgd_model.predict(x_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_sgd)

0.9385964912280702

**Bayesian optimization and early stopping**

* Documentation for hyperopt : https://hyperopt.github.io/hyperopt/
* Documentation for skopt: https://scikit-optimize.github.io/stable/
* Documentaion for Optuna: https://optuna.readthedocs.io/en/stable/